language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  - DJANGO=Django==1.7.8
  - DJANGO=Django==1.8.2
  - DJANGO=Django==1.9b1

matrix:
  exclude:
    - python: 3.5
      env: DJANGO=Django==1.7.8
    - python: 3.3
      env: DJANGO=Django==1.9b1

install:
  - pip install -q $DJANGO
  - pip install coveralls
  - python setup.py -q install

before_script:
  - rm -rf build

script:
  - coverage run --source=registration setup.py test

after_success:
  - coveralls --verbose
