# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.IntegerField(choices=[(0, 'Practice area'), (1, 'Client'), (2, 'Managed delivery')])),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('staff_number', models.IntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('practice_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='MonthControlRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day_of_month', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Locked'), (2, 'Closed')], default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='RowControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=200)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Activity')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Department')),
                ('month_control_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.MonthControlRecord')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='row_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.RowControl'),
        ),
    ]
